### PR TITLE
added three new icons

### PR DESCRIPTION
**Pull request by EricBenjamin**

### CODE REVIEW

**Comment by EricBenjamin** [comment]
@tdumitrescu ping

**Comment by tdumitrescu** [comment]
One of these things is not like the others:
screen shot 2017-02-22 at 6 36 15 pm
Going to assign this PR to @jayjo - do you care about things like icons staying consistently within a standard box, centered, etc? If so then `correlate` and `opportunity` should be nudged. If not then go ahead and hit the big merge button.

**Comment by EricBenjamin** [comment]
That's odd.. those were centered initially. I'm currently unsure how to resolve this. @jayjo can you assist plz.

**Comment by jayjo** [comment]
Should be good to go here folks. 

Unrelated, @tdumitrescu I see you told Eric to hit the big merge button. Are we as designers allowed to do that?

**Comment by tdumitrescu** [comment]
Heh well it won't get published until someone with permissions does it, so it makes sense to have a dev do it anyway. @jbwyme can you take care of this while I'm OOO?

**Comment by EricBenjamin** [comment]
Travis is seriously the worst. What's his deal?

**Comment by jbwyme** [comment]
published in version 0.49.0!

**Pull request merged**
